databases:
  - name: cvflow-db
    databaseName: cvflow
    user: cvflow
    plan: free # ⇧ súbelo a “starter” si necesitas +RAM

services:
  # ────────────────────── FRONTEND ──────────────────────
  - name: frontend
    type: web
    env: docker
    rootDir: frontend
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    buildFilter:
      paths: ["frontend/**"]
    envVars:
      - key: VITE_API_URL
        value: "https://gateway-{{ env.RAILWAY_SERVICE_ID }}.onrender.com"

  # ─────────────────────── GATEWAY ──────────────────────
  - name: gateway
    type: web
    env: docker
    rootDir: gateway
    dockerfilePath: Dockerfile
    plan: free
    buildFilter:
      paths: ["gateway/**"]
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: cvflow-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: cvflow-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: cvflow-db
          property: password
      - key: RABBITMQ_HOST
        value: rabbitmq
      - key: RABBITMQ_PORT
        value: "5672"

  # ──────────────────── MICRO‑SERVICIOS ───────────────────
  - name: core-service
    type: pserv
    env: docker
    rootDir: core-service
    dockerfilePath: core-service/Dockerfile
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: cvflow-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: cvflow-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: cvflow-db
          property: password
      - key: RABBITMQ_HOST
        value: rabbitmq
      - key: RABBITMQ_PORT
        value: "5672"

  - name: ai-service
    type: pserv
    env: docker
    rootDir: ai-service
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: RABBITMQ_HOST
        value: rabbitmq
      - key: RABBITMQ_PORT
        value: "5672"

  - name: cv-parser
    type: pserv
    env: docker
    rootDir: cv-parser
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: RABBITMQ_HOST
        value: rabbitmq
      - key: RABBITMQ_PORT
        value: "5672"

  # ─────────────────────── RabbitMQ ───────────────────────
  - name: rabbitmq
    type: pserv
    runtime: image
    image:
      url: docker.io/library/rabbitmq:3-management
    autoDeploy: false
    plan: free
